print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/alvinwong/Desktop/pacman_unity/pacmangame/Assets/Characters/Pacman/pacman.ma"`)
{		
	file -o "/Users/alvinwong/Desktop/pacman_unity/pacmangame/Assets/Characters/Pacman/pacman.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/alvinwong/Desktop/pacman_unity/pacmangame/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/alvinwong/Desktop/pacman_unity/pacmangame/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/alvinwong/Desktop/pacman_unity/pacmangame/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
